
---
# tasks file for roles/apache


- name: Install {{ apache_webserver_package }}
  yum:
    name: "{{ apache_webserver_package  }}"
    state: latest
- name: install {{ apache_firewall_package  }}
  yum:
    name: "{{ apache_firewall_package  }}"
    state: latest
- name: Start and enable {{ apache_webserver_server }} service
  service:
    name: "{{ apache_webserver_server }}"
    state: started
    enabled: yes
- name: Start and enable {{ apache_firewall_server }} service
  service:
    name: "{{ apache_firewall_server }}"
    state: started
    enabled: yes
- name: Allow {{ apache_firewall_rule }} in firewall
  firewalld:
    service: "{{ apache_firewall_rule }}"
    state: enabled
    immediate: yes
    permanent: yes
- name: Create a home page
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
  notify: restart httpd

